# Generated by Django 3.1.7 on 2021-03-01 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210301_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='starting_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
